name: Next Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/homestay_fe/Homstay
          git fetch origin
          git checkout main
          git reset --hard HEAD
          git pull
          npm install
          npm run build
          pm2 reload homestay
          /root/.nvm/versions/node/v23.11.0/bin/npm
          /root/.nvm/versions/node/v23.11.0/bin/pm2
