name: Next Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          set -x
          export NVM_DIR="$HOME/.nvm"  # Đảm bảo nvm được cài đúng đường dẫn
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Nạp nvm
          nvm install 23.11.0  # Cài đặt phiên bản Node.js nếu chưa có
          nvm use 23.11.0  # Sử dụng phiên bản Node.js
          
          # Kiểm tra lại node, npm và pm2
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "PM2 version: $(pm2 -v)"
          
          # Quá trình deploy
          cd /root/homestay_fe/Homstay
          git fetch origin
          git checkout main
          git reset --hard HEAD
          git pull
          npm install --legacy-peer-deps
          npm run build
          pm2 reload homestay
